ARG RUBY_VERSION=3.1.2
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim as base

RUN apt-get update -qq && apt-get install -y build-essential apt-utils libpq-dev nodejs curl libvips postgresql-client

WORKDIR /docker/app

RUN gem install bundler

COPY Gemfile* ./
COPY tmp/ ./

RUN bundle install

ADD . /docker/app

ARG DEFAULT_PORT 3000

EXPOSE ${DEFAULT_PORT}

CMD [ "bundle","exec", "puma", "config.ru"] # CMD ["rails","server"] # you can also write like this.